### ISSUE TITLE
How can we run this matlab program 

### ISSUE THREAD

**Issue by shaikmohammadyounus982** [Anirudh2305/Photon-Transport-Monte-Carlo-UWOC#2]
How can we run these programs. I mean which program should we run first to get the results

**Comment by Anirudh2305** [comment]
Here's the order you can follow:
1) Signum.m
2) Hen_Green.m
3) Photon.m
4) Now you can run any of Monte_carlo.m/ MCScript.m/ CIR.m/ Novelty.m (all these files run independently and depend only on the first 3 files).
